# 1
name: Build Debug Apk
# 2
on:
  create:
    tags:
      - v*

# 3
jobs:
  build:
    # 4
    name: Build and Upload apk
    # 5
    runs-on: ubuntu-latest
    # 6
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
         java-version: '1.8'
      - name: Build Apk
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
         name: app.apk
         path: app/build/outputs/apk/debug/MMCurrencyExchange-debug.apk
      - name: Release asset
        uses: softprops/action-gh-release@v1
        with:
          body: "A new release"
          files: app/build/outputs/apk/debug/MMCurrencyExchange-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

